const js = require('@eslint/js');
const importX = require('eslint-plugin-import-x');
const tseslint = require('typescript-eslint');

const ignores = {
  ignores: [
    'types',
    'cjs',
    'esm',
    'src/**/*.test.ts',
    'src/**/*.test_.ts',
    'src/lib/Help.ts' /* generated by scripts/generate-help.mjs */,
    'tsup.config.ts',
  ],
};

const rules = {
  '@typescript-eslint/no-explicit-any': 'off',
  '@typescript-eslint/no-deprecated': 'warn',
  'dot-notation': 'off',
  'no-console': 'warn',
  'no-underscore-dangle': 'off',
  'no-restricted-syntax': ['error', 'LabeledStatement', 'WithStatement'],
  'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: 'tinyrainbow',
          message:
            "Import color from './utils/ColorTheme' (relative path may vary) instead of 'tinyrainbow' directly, so the color palette stays centralized in one place.",
        },
      ],
    },
  ],
  'no-multi-str': 'off',
  'import-x/first': 'error',
  'import-x/newline-after-import': 'error',
  'import-x/no-duplicates': 'error',
};

module.exports = tseslint.config(
  ignores,
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: __dirname,
      },
    },
    plugins: {
      'import-x': importX,
    },
    rules,
  },
  {
    files: ['src/utils/ColorTheme.ts'],
    rules: {
      'no-restricted-imports': 'off',
    },
  }
);
